### ISSUE TITLE
Instagram - 405 Error

### ISSUE THREAD

**Issue by safdarzeeshan** [st4lk/django-rest-social-auth#8]
I've been using this library for a few months and its great :)
I saw this issue 2 days ago where a user cannot login. I get a stack trace from my backend

```
405 Client Error: METHOD NOT ALLOWED for url: https://www.instagram.com/oauth/access_token
Traceback (most recent call last):
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/rest_social_auth/views.py", line 108, in post
    user = self.get_object()
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/rest_social_auth/views.py", line 142, in get_object
    user = self.request.backend.complete(user=user)
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/social/backends/base.py", line 41, in complete
    return self.auth_complete(*args, **kwargs)
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/social/utils.py", line 229, in wrapper
    return func(*args, **kwargs)
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/social/backends/oauth.py", line 383, in auth_complete
    method=self.ACCESS_TOKEN_METHOD
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/social/backends/oauth.py", line 361, in request_access_token
    return self.get_json(*args, **kwargs)
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/social/backends/base.py", line 229, in get_json
    return self.request(url, *args, **kwargs).json()
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/social/backends/base.py", line 225, in request
    response.raise_for_status()
  File "/Users/zeeshan/projects/django-rest-example/env/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 405 Client Error: METHOD NOT ALLOWED for url: https://www.instagram.com/oauth/access_token
```

I thought I had made some code changes but downloaded the original example project again and added an instagram auth. The same issue occured. Is there any know issue with instagram?

**Comment by st4lk** [comment]
Hi Zeeshan, thanks for reporting!
Looks like it is related to [python-social-auth issue](https://github.com/omab/python-social-auth/issues/796).

So we have to wait until this issue will be merged in python-social-auth.

Currently, you can use following workaround:

1. Subclass InstagramOAuth2 and define ACCESS_TOKEN_URL somewhere in your app:

        from social.backends.instagram import InstagramOAuth2 as BaseInstagramOAuth2

        class InstagramOAuth2(BaseInstagramOAuth2):
            ACCESS_TOKEN_URL = 'https://api.instagram.com/oauth/access_token'

2. Use it instead of `'social.backends.instagram.InstagramOAuth2'` in settings:

        AUTHENTICATION_BACKENDS = (
            # ...
            'yourapp.module.InstagramOAuth2',
            # ...
        )

**Comment by safdarzeeshan** [comment]
Thank you so much. That fixed the issue. And again great work with the library, really made my life much easier :)
